### ISSUE TITLE
Connection failure from python client

### ISSUE THREAD

**Issue by tscholak** [facebookincubator/hsthrift#36]
Hi,

After working around #35, I've worked further towards an implementation with a Haskell server and a Python client. However, I've encountered the next problem:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 281, in open
    handle = socket.socket(res[0], res[1])
  File "/opt/conda/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  transport.open()
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TTransport.py", line 173, in open
    return self.__trans.open()
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 301, in open
    raise TTransportException(TTransportException.NOT_OPEN, msg)
thrift.transport.TTransport.TTransportException: socket error connecting to host localhost, port 9090 (('::1', 9090, 0, 0)): OSError(97, 'Address family not supported by protocol')
```

I've pip-installed the `Thrift` library that is shipped with `fbthrift`, and I'm opening the socket like so:
```py
from thrift.transport import TTransport
from thrift.transport import TSocket

transport = TSocket.TSocket("localhost", 9090)
transport = TTransport.TBufferedTransport(transport)

...

transport.open()
```
While I'm executing this script, the server is running already in the background on the same host.

I've tried replacing `localhost` with `127.0.0.1`, but to no avail. In that case, the error becomes:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 286, in open
    handle.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  transport.open()
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TTransport.py", line 173, in open
    return self.__trans.open()
  File "/opt/conda/lib/python3.8/site-packages/thrift/transport/TSocket.py", line 301, in open
    raise TTransportException(TTransportException.NOT_OPEN, msg)
thrift.transport.TTransport.TTransportException: socket error connecting to host 127.0.0.1, port 9090 (('127.0.0.1', 9090)): ConnectionRefusedError(111, 'Connection refused')
```

Can you please confirm that there's nothing fundamentally wrong with my assumption that Python-Haskell connections are currently supported and that the Python code posted above is correct.

Thanks!

**Comment by tscholak** [comment]
Ah, I think I know what's going on: the port the server chooses is random!

**Comment by zsol** [comment]
This should be supported, yes. And correct, it sounds like the server is not listening on the port the python client is trying to connect to.

**Comment by tscholak** [comment]
Indeed, that was it, closing. Thanks!
